module.exports = {
  api: require('./api'),
  close: require('./close'),
  connect: require('./connect'),
  db: require('./db'),
  delete: require('./delete'),
  get: require('./get'),
  insert: require('./insert'),
  insertAll: require('./insertAll'),
  reconnect: require('./reconnect'),
  replace: require('./replace'),
  run: require('./run'),
  sync: require('./sync'),
  table: require('./table'),
  tableCreate: require('./tableCreate'),
  tableDrop: require('./tableDrop'),
  tableList: require('./tableList'),
  update: require('./update'),
  use: require('./use')
}